- .coveragerc
- kashgari/__init__.py
- kashgari/corpus.py
- kashgari/tasks/classification/base_model.py
- kashgari/tasks/seq_labeling/__init__.py
- kashgari/tasks/seq_labeling/base_model.py
- setup.py
- tests/test_classifier_models.py
- tests/test_seq_labeling_models.py
* add `output_dict`, `debug_info` params to text_classification model
* add `output_dict`, `debug_info` and `chunk_joiner `params to text_classification model
* fix possible crash at data_generator
> release v0.1.6

- kashgari/embeddings/embeddings.py
- kashgari/tasks/classification/base_model.py
- setup.py
- version.py
* remove class candidates filter to fix #16
* overwrite init function in CustomEmbedding
* add parameter check to custom_embedding layer
* add `keras-bert` version to setup.py file
> fix several minimal details

- kashgari/tasks/classification/__init__.py
- kashgari/tasks/classification/deep_models.py
- kashgari/tasks/classification/shadow_models.py
As mentioned in #16 , I hacked the original models under `tasks.classification` to alter the activation layer type of them to `softmax`, which I put in the file `shadow_models.py`.
I also refactored several deep models structures into child classes, so they could be directly used in `Kashgari`, which I put in the file `deep_models.py`.
Hope to be helpful.
> modified and add some models

- kashgari/layers.py
- kashgari/tasks/base/base_model.py
- kashgari/tasks/classification/models.py
As mentioned in title and commits.
Feel so happy to be able to make this PR.
> Develop - Fix shape mismatch bug in KMaxPooling, improve save load robust and config flexibility

- kashgari/tasks/base/base_model.py
- kashgari/tasks/classification/base_model.py
- kashgari/tasks/classification/models.py
- tests/test_classifier_models.py
* add multi-label classification for all classification models
> finish multi-label classification function

- README.md
- kashgari/tasks/classification/base_model.py
- kashgari/tasks/classification/models.py
- kashgari/tasks/seq_labeling/base_model.py
- kashgari/tasks/seq_labeling/blstm_crf_model.py
- kashgari/tasks/seq_labeling/blstm_model.py
- kashgari/tasks/seq_labeling/cnn_lstm_model.py
Support for training on multiple GPUs.
Example:
```python
from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.classification import CNNLSTMModel
bert_embedding = BERTEmbedding('bert-large-cased', sequence_length=128)
model = CNNLSTMModel(bert_embedding)
model.build_multi_gpu_model(gpus=8)
train_x, train_y = prepare_your_classification_data()
model.fit(train_x, train_y, batch_size=256)
```
> features: multi-gpu support

- kashgari/tasks/base_model.py
Hello team,
Apparently there is a typo in the new branch. Without a validation, the number of steps was always 3
> Wrong number of epochs

- kashgari/tasks/classification/models.py
Available to make some work from this week on.
Here are two models for instance.
Try to make naming compatibility with former versions while providing new naming style.
> :construction: rewrite classification models under tf.keras schema

- kashgari/layers/att_wgt_avg_layer.py
- kashgari/layers/kmax_pool_layer.py
- kashgari/tasks/classification/models.py
- tests/classification/test_bi_lstm.py
Unit test passed, finally, by modifying test causes errors. 👻
> Tf.keras version models zoo constructed, first batch.

- kashgari/tasks/base_model.py
- kashgari/utils.py
```python
import kashgari
from kashgari.corpus import ChineseDailyNerCorpus
from kashgari.tasks.labeling import BiLSTM_Model
train_x, train_y = ChineseDailyNerCorpus.load_data('train', shuffle=False)
model = BiLSTM_Model()
model.build_multi_gpu_model(2, True, False, train_x, train_y)
model.fit(train_x, train_y)
```
> Fix Raising InvalidArgumentError when using `utils.convert_to_multi_gpu_model`

- kashgari/tasks/classification/__init__.py
- kashgari/tasks/classification/dpcnn_model.py
> :sparkles: add DPCNN to model zoo

- README.md
- docs/CHANGELOG.md
- docs/index.rst
- docs/md/home.md
- kashgari/version.py
This is tf.keras rewrite version. Here are the highlights.
- 🎉 Rewrite Kashgari using `tf.keras`. Discussion: [#77](https://github.com/BrikerMan/Kashgari/issues/77)
- 🎉 Rewrite Documents.
- ✨ Add TPU support.
- ✨ Add TF-Serving support.
- ✨ Add advance customization support, like multi-input model.
- 🐎 Performance optimization.
> :bookmark: Release 0.5.0

- kashgari/embeddings/base_embedding.py
- kashgari/embeddings/bert_embedding.py
- kashgari/tasks/base_model.py
- kashgari/tasks/classification/base_model.py
- kashgari/tasks/classification/models.py
- kashgari/tasks/labeling/base_model.py
- mkdocs/docs/about/release-notes.md
- mkdocs/docs/api/callbacks.md
- mkdocs/docs/api/tasks.classification.md
- mkdocs/docs/api/tasks.labeling.md
- mkdocs/docs/api/utils.md
- mkdocs/docs/embeddings/bert-embedding.md
- mkdocs/mkdocs.yml
- tests/classification/test_bi_lstm.py
- 📝 Rewrite documents with mkdocs
- 📝 Add Chinese documents
- 🚸 Add `label2idx`, `token2idx` properties to Embeddings and Models
- ✨ Add `predict_top_k_class` for classification model to get predict probabilities ([#146](https://github.com/BrikerMan/Kashgari/issues/146))
- 🚸 Add `tokenizer` property for BERT Embedding. ([#136](https://github.com/BrikerMan/Kashgari/issues/136))
- 🚸 Add `predict_kwargs` for models `predict()` function
- ⚡️ Change multi-label classification's default loss function to binary_crossentropy ([#151](https://github.com/BrikerMan/Kashgari/issues/151))
> Release v0.5.1

- mkdocs/docs/FAQ.md
- mkdocs/docs/about/release-notes.md
- mkdocs/docs/embeddings/bert-embedding.md
- mkdocs/mkdocs.yml
- :memo: Add documents about How to resume training with a saved checkpoint file. #117
- 📝 Add documents about using a sentence pair input with BERT. #155
> :pencil: Adding documents

- kashgari/tasks/base_model.py
> shuffle on demand

- kashgari/utils.py
- mkdocs/docs/tutorial/text-classification.md
- mkdocs/docs/tutorial/text-labeling.md
- tests/labeling/test_cnn_lstm_model.py
* 🐛 fixed loading models with `CRF` layers (#244, #228)
* ❇️ improved type hinting (#248)
> fix load_model

- README.md
- kashgari/__init__.py
- kashgari/callbacks.py
- kashgari/embeddings/gpt_2_embedding.py
- kashgari/macros.py
- kashgari/migeration.py
- kashgari/processors/base_processor.py
- kashgari/tasks/base_model.py
- kashgari/version.py
- mkdocs/docs/about/release-notes.md
- mkdocs/docs/index.md
- setup.tf.py
Unfortunately, we renamed again for consistency and clarity. Here is the new naming style.
| Backend          | pypi version   | desc           |
| ---------------- | -------------- | -------------- |
| TensorFlow 2.x   | kashgari 2.x.x | coming soon    |
| TensorFlow 1.14+ | kashgari 1.x.x |                |
| Keras            | kashgari 0.x.x | legacy version |
Here is how the existing versions changes
| Supported Backend | Kashgari Versions | Kahgsari-tf Version |
| ----------------- | ----------------- | ------------------- |
| TensorFlow 2.x    | kashgari 2.x.x    | -                   |
| TensorFlow 1.14+  | kashgari 1.0.1    | -                   |
| TensorFlow 1.14+  | kashgari 1.0.0    | 0.5.5               |
| TensorFlow 1.14+  | -                 | 0.5.4               |
| …
> Release v1.0.0

- kashgari/processors/base_processor.py
> fix processor

- kashgari/processors/classification_processor.py
- tests/classification/test_bi_lstm.py
- :bug: Fixing multi label classification model loading. #304
> :bug: Fixing multi label classification model loading. #304

- .travis.yml
- kashgari/tokenizer/__init__.py
- kashgari/tokenizer/base_tokenizer.py
- kashgari/tokenizer/bert_tokenizer.py
- kashgari/tokenizer/jieba_tokenizer.py
- tests/test_tokenizer.py
> :sparkles: Add tokenizers.

- docs/about/release-notes.md
- docs/embeddings/bert-embedding.md
- docs/embeddings/index.md
- kashgari/__init__.py
- kashgari/embeddings/base_embedding.py
- kashgari/embeddings/stacked_embedding.py
- kashgari/tasks/labeling/models.py
- kashgari/utils.py
- 🐛 Fix transformer embedding error, loaded custom objects. ([#358])
> Release 1.1.5
